[Variables]
DownloadSpeed=(3.6 * 1048576)
UploadSpeed=(0.39 * 1048576)
RecycleBinSize=(5 * 1073741824)
MaxPing=200
HardDrive1=C
HardDrive2=D
;--------------------------------
FadeTime=50
;--------------------------------
TextFont=ITC Avant Garde Pro Xlt
ClockFontSize=170
ClockFontWeight=300
DateFontSize=25
DateFontWeight=700
TitleFontSize=12
TitleFontWeight=300
DefaultFontSize=10
DefaultFontWeight=100
GreyBarColor=255,255,255,50
GreyTextColor=255,255,255,200