[Variables]
; PLEASE CUSTOMIZE THESE VARIABLES
;----------------------------------

; Your maximum download and upload speed.
; Only change the first number (before the '*' character) to your maximum download/upload speed in Mbps
; If you are unsure about what this is, more info here : https://docs.rainmeter.net/tips/network-skin/ §Setting the MinValue / MaxValue options
DownloadSpeed=(3.6 * 1048576)
UploadSpeed=(0.39 * 1048576)

; Chage the first number (before the '*' character) to your Windows' recycle bin size limit in GB (or Go)
; If you left it unlimited, then enter 0
RecycleBinSize=(5 * 1073741824)

; This is the maximum ping in ms you expect to encounter on a regular basis
MaxPing=200

; Those are the alphabetical identifiers of the hard drives you want to monitor
HardDrive1=C
HardDrive2=D


; YOU DON'T NEED TO MESS WITH THOSE
;----------------------------------

; Time in ms the color fading should take when the wallpaper changes
FadeTime=50

; Police, size and weight of each text
TextFont=ITC Avant Garde Pro Xlt
ClockFontSize=170
ClockFontWeight=300
DateFontSize=25
DateFontWeight=700
TitleFontSize=12
TitleFontWeight=300
DefaultFontSize=10
DefaultFontWeight=100
GreyBarColor=255,255,255,50
GreyTextColor=255,255,255,200